moodle-an-hochschulen/moodle-theme_boost_union

- CHANGES.md
- README.md
- db/access.php
- lang/en/theme_boost_union.php
- layout/columns2.php
- layout/drawers.php
- lib.php
- locallib.php
- scss/boost_union/post.scss
- settings.php
- templates/columns2.mustache
- templates/course-hint-guestaccess.mustache
- templates/course-hint-hidden.mustache
- templates/course-hint-selfenrol.mustache
- templates/course-hint-switchedrole.mustache
- templates/drawers.mustache
- tests/behat/theme_boost_union_course_settings.feature
This patch ports the 'course related hints' feature from Boost Campus to Boost Union.
With this patch, four new settings are introduced:
* Position of switch role information
* Show hint in hidden courses
* Show hint guest for access
* Show hint for self enrolment without enrolment key
The implementation is more or less the same as it was in Boost Campus, but the rendering of the hints are changed from html_writer to Mustache templates.
> Add course related hints feature, solves #5

- CHANGES.md
- README.md
- db/access.php
- lang/en/theme_boost_union.php
- settings.php
- tests/behat/theme_boost_union_managers.feature
- version.php
This patch introduces the theme/boost_union:configure capability which allows managers to configure the theme as non-admin. By default, the capability is assigned to no role at all.
----
Please note that this PR is built on top of PR #31 and should be merged in line.
> Feature: Allow non-admins to edit theme settings, solves #28

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- layout/columns2.php
- layout/drawers.php
- layout/includes/javascriptdisabledhint.php
- settings.php
- templates/columns2.mustache
- templates/drawers.mustache
- templates/javascriptdisabledhint.mustache
- tests/behat/theme_boost_union_misc_settings.feature
With this patch, the admin can enable a hint which will appear at the top of the Moodle page if JavaScript is not enabled. This is particularly helpful as several Moodle features do not work without JavaScript.
----
Please note that this PR is built on top of PR #45 and should be merged in line.
> Feature: Show a warning banner if JavaScript is disabled, solves #46

- scss/boost_union/post.scss
Currently the "Back to top" button floats over the right drawer when it is shown (see screenshot).
This pull request moves it over the main content to line up with the floating footer button.
> Move back to top button when right drawer is shown

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- lib.php
- settings.php
- tests/behat/theme_boost_union_branding_settings.feature
- version.php
With this patch, the admin can customize the activity icon background colors which were introduced in Moodle 4.0
> Feature: Customize activity icon background colors, solves #49

- CHANGES.md
- lang/en/theme_boost_union.php
- settings.php
- tests/behat/theme_boost_union_branding_settings.feature
- tests/behat/theme_boost_union_managers.feature
Currently, this theme's settings are combined within one single tabbed settings page as Boost theme settings are built normally.
However, as we are and will be using many hide_if constraints for our settings, we would run into the
stupid "Too much data passed as arguments to js_call_amd..." debugging message if we would
continue to pack all settings onto just one settings page.
To achieve this goal, we will create a custom admin settings category and fill it with several settings pages.
> Settings: Divide theme settings into multiple pages, solves #52

- CHANGES.md
- classes/output/core_renderer.php
- lib.php
- scss/boost_union/post.scss
- templates/footnote.mustache
- version.php
#106 - This patch solves the problem that the footnote content was not really readable as soon as a background image was configured. Additionally, it improves the margins and paddings of the footnote on the various screen sizes.
#107 - This patch changes the way how the login page background is added to the page from the #page element to the body element.
Additionally, it introduces several adjustments to make sure that the footnote works well with background images on the login page.
Here's how it looks like now:
> Footnote and Login background - Bugfixes for #106 and #107

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- lib.php
- locallib.php
- scss/boost_union/post.scss
- settings.php
- templates/settings-additionalresources-filelist.mustache
- tests/behat/theme_boost_union_looksettings_resources.feature
- version.php
With this patch, a setting is added where the admin can upload additional resources to the theme which can be linked from anywhere in Moodle (especially from custom CSS).
> Feature: Filearea for additional resources, solves #113

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- locallib.php
- settings.php
- templates/core/email_html.mustache
- templates/core/email_html.mustache.upstream
- templates/core/email_text.mustache
- templates/core/email_text.mustache.upstream
- templates/emailpreview.mustache
- tests/behat/theme_boost_union_looksettings_emailbranding.feature
- version.php
As announced in #60, I have implemented a workaround solution to at least override the email templates within Boost Union.
This patch introduces a new settings tab with a step-by-step explanation what to do:
As soon as you have customized your language pack, you will see previews of the branded emails:
Unfortunately, the Behat tests are still failing and I don't know why yet. It seems as if the theme's language pack strings are not registered in the language pack customization.
Maybe @lucaboesch has an idea.
> Feature: Allow admins to override the email templates within the theme, solves #60

- CHANGES.md
- README.md
- classes/admin_setting_configstoredfilealwayscallback.php
- db/caches.php
- lang/en/theme_boost_union.php
- lib.php
- locallib.php
- settings.php
- templates/settings-fontawesome-checks.mustache
- templates/settings-fontawesome-filelist.mustache
- tests/behat/theme_boost_union_looksettings_resources.feature
This patch introduces a new setting in the Look -> Resources tab which allows the admin to upload FontAwesome 6 Free files and add them to Moodle.
As soon as some files are uploaded, a file list is shown which helps the admin to identify the remaining files and which tells him which files are mandatory and which are optional:
Finally, there is a checks section which helps the admin to assess if everything is working correctly:
During the implementation of this patch, some decisions have been made:
* Currently, only FontAwesome 6 Free is supported. However, the architecture is already built in a way to allow the addition of FontAwesome 6 Pro quite easily. I will create a follow-up issue for that.
* Currently, FontAwesome 5 is not supported. It seemed not to make much sense to allow …
> Feature: Possibility to upload FA 6 Free to the theme, solves #59

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- locallib.php
- mobile/styles.php
- settings.php
- tests/behat/theme_boost_union_looksettings_mobile.feature
- version.php
Implements #195 (Add tab mobile and text field setting to add css to mobile layout).
> Added Tab and setting to upload mobilcss rules

- CHANGES.md
- scss/boost_union/post.scss
- templates/advertisementtiles.mustache
This PR realizes the look which has been posted in #232
> Bugfix: Improve card header and footer of advertisement tiles with background images, solves #232

- CHANGES.md
- config.php
boost_union doesn't provide any editor.scss. By setting it, it unnecessarily blocks boost's own editor.scss inclusion.
> #242 - removed editor_scss config

- CHANGES.md
- layout/login.php
login.php explicitly used the current theme's settings to check for 'loginformposition' and 'loginformtransparency'. Using Boost Union's configuration doesn't require child themers to reimplement those settings.
> #247 - reduce settings duplication for child theming

- CHANGES.md
- lib.php
Changed all instances of $theme->settings in theme_boost_union_get_pre_scss to get_config('theme_boost_union') to prevent child theme settings duplication
> #260 - Explicitly use boost union's color settings

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- layout/drawers.php
- settings.php
- tests/behat/theme_boost_union_feelsettings_blocks.feature
This PR adds the following functionality to boost_union:
- Added section "Right-hand block drawer" to "Feel -> Blocks" admin settings
- Added functionality: configure right-hand block drawer to be shown on the frontpage without being logged in
- Added functionality: configure right-hand block drawer to be shown on a users first login
- Added functionality: configure right-hand block drawer to be shown for guest users
All changes to the right-hand block drawer behaviour do not impact the state management for users who have interacted with the open/closed state.
> Feature: Allow right-side blocks drawer of the home-page to be extended by default, closes #169

- CHANGES.md
- scss/boost_union/post.scss
This pull request solves issue #273.
Furthermore, it improves the look of the primary color navbar with the dark text, changes the color of the language menu for not logged-in users. 
For clarification, what this PR is about: 
Before
After
Before
After
Before
After
Before
After
Before
After
Before
After
Before
After
> Improvement: Improve SCSS for dark navbar and primary color navbar, solves #273.

- CHANGES.md
- scss/boost_union/post.scss
Adding the flex-grow-1 class to the new .main-inner-wrapper element fixes the problem.
Before
After
> Bugfix: Fix footer and footnote placement, solves #269.

- CHANGES.md
- renderers.php
This PR adds related styles and scripts of both `och5p` plugins (`local_och5p` and `local_och5pcore`).
It fixes the related issue for both plugins in:
* https://github.com/Opencast-Moodle/moodle-local_och5p/issues/8
* https://github.com/elan-ev/moodle-local_och5pcore/issues/4
It completed #354
> Fix for och5p plugins compatibility

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- layout/includes/staticpages.php
- pages/aboutus.php
- pages/offers.php
- pages/page1.php
- pages/page2.php
- pages/page3.php
- settings.php
- templates/footnote.mustache
- templates/theme_boost/footer.mustache
- tests/behat/behat_theme_boost_union.php
- tests/behat/theme_boost_union_contentsettings_staticpages.feature
- version.php
This patch adds five additional static pages:
- About us
- Offers
- Generic page 1
- Generic page 2
- Generic page 3
> Improvement: Add more static pages, solves #351.

- CHANGES.md
- locallib.php
Solves #369. Looked at the remove_dir code and couldn't see any difference (apart from the bool parameter negation).
> #369 - Improvement: Reuse Moodle core function remove_dir()

- CHANGES.md
- locallib.php
- templates/emailpreview.mustache
I have tested this fix on recent Firefox and Chrome browsers and it worked. However, as it uses the Shadow DOM feature, testing on other / older browsers might be good.
Testing instructions can be found here: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/413#issuecomment-1757843468
> Bugfix: Styles of styled e-mail previews leaked into the rest of the admin UI, solves #413.

- CHANGES.md
- scss/boost_union/post.scss
On Moodle 4.3, the page is scrolled up automatically on smaller screens as soon as the right hand drawer is opened. Thus, this bug does not really affect Moodle 4.3.
However, I have also tested this patch on 4.2 and 4.1 (to which it will be backported, of course, during the next release) and it solves the bug there nicely.
> Bugfix: Hide back to top button on small screens as soon as the right hand drawer is opened, solves #379.

- CHANGES.md
- scss/boost_union/post.scss
Before:
After:
This was a quick fix in CSS, but it should be sufficient from my point of view.
While the "bulk actions" widget on Moodle 4.3 is the first widget where I realized this header actions area myself, the header actions area has been there before on Moodle 4 already and might be filled by course formats or plugins. Thus, it should be safe to backport this patch to pre-4.3 versions of Boost Union as well.
> Bugfix: Bulk actions widget overlaid course header image, solves #469.

- CHANGES.md
- templates/core/loginform.mustache
- templates/core/loginform.mustache.upstream
OAuth2 login button was transparent.
Adding btn-secondary class to this button solves the missing background color problem.
Before:
After:
> Bugfix: Add background color to OAuth2 login button, solves #473.

- lang/en/theme_boost_union.php
There's no such thing as a "theme_boost_union language" setting. The ```<code>```  tags should end earlier.
> Update emailbrandinginstructionli2 string in lang/en/theme_boost_union.php

- CHANGES.md
- README.md
- classes/output/core_renderer.php
- lang/en/theme_boost_union.php
- layout/columns2.php
- layout/drawers.php
- layout/includes/footer.php
- layout/login.php
- lib.php
- scss/boost_union/post.scss
- settings.php
- templates/theme_boost/drawers.mustache
- templates/theme_boost/footer.mustache
- tests/behat/theme_boost_union_contentsettings_footer.feature
- version.php
I've been given the code mentioned here https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/6#issuecomment-1525411812 thanks to @goggo24 and @moniNaydenov and I have built upon that one.
Thanks heaps!
> Improvement: Add the option to suppress the footer button, solves #444.

- CHANGES.md
- README.md
- classes/output/core_renderer.php
- lang/en/theme_boost_union.php
- settings.php
- templates/core/loginform.mustache
- tests/behat/theme_boost_union_looksettings_loginpage.feature
- version.php
This PR introduces two new settings to hide the local login form and the IDP login intro on the login page
Before:
After:
> Feature: Allow the admin to hide the manual login form, solves #490.

- CHANGES.md
- classes/local/hook/output/before_standard_head_html_generation.php
- db/hooks.php
- lib.php
- locallib.php
This patch is mainly targeted towards the upcoming Moodle 4.4 release, but it is implemented in a backwards-compatible way. 
It has been tested by me manually in 4.4dev. As soon as the tests of the PR (on 4.3) are green, it can be merged.
> Upgrade: Migrate the before_standard_html_head() function to the new hook callback on Moodle 4.4, resolves #604.

- CHANGES.md
- settings.php
- tests/behat/behat_theme_boost_union_base_smartmenus.php
- tests/behat/theme_boost_union_flavourssettings_application.feature
- tests/behat/theme_boost_union_flavourssettings_caching.feature
- tests/behat/theme_boost_union_flavourssettings_look.feature
- tests/behat/theme_boost_union_flavourssettings_management.feature
- tests/behat/theme_boost_union_general.feature
- tests/behat/theme_boost_union_goodiesfordesigners.feature
- tests/behat/theme_boost_union_looksettings_h5p.feature
- tests/behat/theme_boost_union_looksettings_scss.feature
- tests/behat/theme_boost_union_managers.feature
This PR ships with a commended Behat test in tests/behat/theme_boost_union_general.feature which cannot be uncommented before Moodle 4.4
I will create a follow-up issue to uncomment it on 4.4.
> Upgrade: Boost Union settings were moved to an admin settings category of its own to support the new theme chooser on Moodle 4.4, resolves #482.

- lib.php
I did not add anything to CHANGES.md as there has not been any release between the integration of #605 and this PR.
> Regression: Migrating the before_standard_html_head() function to the new hook callback broke the login page on Moodle 4.3, resolves #613

- CHANGES.md
- templates/theme_boost/drawers.mustache
- tests/behat/theme_boost_union_contentsettings_advertisementtiles.feature
- tests/behat/theme_boost_union_contentsettings_slider.feature
This PR resolves #488 only partly.
I have commented in #488 what is fixed and what remains.
Issue #488 has to remain open when this PR is merged.
> Bugfix: Site support form success message is now shown above advert tiles / the slider on frontpage, partly resolves #488.

- CHANGES.md
- README.md
- flavours/edit.php
- flavours/preview.php
- lang/en/theme_boost_union.php
- settings.php
- settings_overview.php
- smartmenus/edit.php
- smartmenus/edit_items.php
- smartmenus/items.php
- templates/settings-overview.mustache
- tests/behat/theme_boost_union_general.feature
I refined the PR #609.
There is now a Boost Union settings overview page which looks like this:
On Moodle 4.4dev, it is linked from the theme selector:
and the Appearance page only has the new Boost Union settings category:
On Moodle 4.3, it is linked from the "Boost Union" link which is still auto-generated by Moodle core:
I hope that this is a good compromise between a forward-facing fix for Moodle 4.4 and a not-so-big chance for 4.3 and older Moodle releases.
> Upgrade: Boost Union settings were moved to an admin settings category of its own to support the new theme chooser on Moodle 4.4, refines #482

- CHANGES.md
- classes/boostnavbar.php
- tests/behat/behat_theme_boost_union_behat_navigation.php
- tests/behat/theme_boost_union_feelsettings_navigation.feature
> Bugfix: Correct order for in-course breadcrumb when sections exist in it (First categories then sections)

- CHANGES.md
- README.md
- lang/en/theme_boost_union.php
- locallib.php
- settings.php
- templates/course-hint-hidden.mustache
- tests/behat/theme_boost_union_functionalitysettings_courses.feature
- version.php
This is a follow up for another closed PR: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/109
It solves See Issue https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/98
I changed the logic a bit in comparison to the original Pull-Request: Now a single Mustache template is used for all hint messages for hidden courses.
> #98 further hints on hidden courses

- CHANGES.md
- scss/boost_union/post.scss
Remarks:
* I used absolute px values instead of calculated to be on par with existing css.
* in L2091 I opted to use explicit ID-selectors for nav- and courseindex drawers to be specific enough and omit the !important flag
> fix: smart menu menubar overlays course index, resolves #607

- CHANGES.md
- README.md
- classes/output/core_renderer.php
- lang/en/theme_boost_union.php
- layout/includes/footer.php
- settings.php
- templates/theme_boost/footer.mustache
- tests/behat/theme_boost_union_contentsettings_footer.feature
- version.php
> Improvement: Configurable "Documentation for this page" link in footer, resolves #649.

- CHANGES.md
- README.md
- classes/admin_setting_configtext_url.php
- classes/task/purge_cache.php
- db/tasks.php
- lang/en/theme_boost_union.php
- lib.php
- locallib.php
- settings.php
- tests/behat/theme_boost_union_looksettings_scss.feature
- tests/behat/theme_boost_union_tasks.feature
- tests/fixtures/extscss-invalid.scss
- tests/fixtures/extscss.scss
To allow Github actions to run on the peer review branch, the `tests/behat/theme_boost_union_tasks.feature` and `tests/behat/theme_boost_union_looksettings_scss.feature` files contain references to the issue-41 branch.
As soon as Github actions are green for this PR or during the integration of this PR at the latest, `issue-41` should be replaced with `master` in both files.
> Feature: Allow admins to configure URLs from where Boost Union will fetch additional raw SCSS code, resolves #41

- CHANGES.md
- classes/smartmenu_item.php
This PR should be self-explaining
> Cleanup: Fix 'Implicitly marking a parameter as nullable is deprecated since PHP 8.4' codechecker warning, resolves #667.

- CHANGES.md
- tests/fixtures/extscss-invalid.scss
- tests/fixtures/extscss.scss
This PR is a no-brainer.
As soon as the tests have passed, it can be integrated.
However, we won't know if it really solves the problem which is described in #674 before the next release on moodle.org
> Cleanup: Fix CSS warnings in external SCSS tests, resolves #674.

- CHANGES.md
- lang/en/theme_boost_union.php
- locallib.php
- settings.php
- tests/behat/theme_boost_union_looksettings_scss.feature
- tests/fixtures/extscss-with-variables.scss
The tests of this PR will fail as they try to download a new SCSS file from the master branch. I have run the test locally successfully and they will be green after the branch is integrated into master.
> Bugfix: Allow external SCSS to use SCSS variables by disabling the SCSS validation, resolves #683.

- CHANGES.md
- classes/boostnavbar.php
- tests/behat/theme_boost_union_feelsettings_navigation.feature
This PR fixes the glitch which was reported in #727.
It was caused by a bug in Boost Union on the one hand, but also by the upstream change in MDL-80974 (see https://github.com/moodle/moodle/commit/faac67e2eaa44981eddf2508c35210c8b121f848) on the other hand.
The PR's solution is to remove course category breadcrumbs from the enrolment page entirely as Boost Union in fact never promised to show them, they were rather shown there by chance.
The setting `theme_boost_union | categorybreadcrumbs`says:
> By default, the course category breadcrumbs are not shown on course pages in the course header. With this setting, you can show the course category breadcrumbs in the course header above the course name.
Nothing is mentioned about the enrolment page. If category breadcrumbs are requested there, …
> Bugfix: Course category breadcrumbs were broken on the course enrolment page due to MDL-80974 and were removed, resolves #727

- CHANGES.md
- README.md
- db/caches.php
- lang/en/theme_boost_union.php
- lib.php
- locallib.php
- settings.php
This PR will backport the patch for #721 which was integrated into BU 4.5 into BU 4.4 as well (in a slightly modified way).
The goal is to align both codebases in this aspect.
> Backport: Use the before_session_start() callback instead of the after_config() callback on Moodle 4.4, resolves #721.

- tests/behat/theme_boost_union_smartmenusettings_menus_presentation.feature
Another summer time _theme_boost_union_ fix.
This targets at solving the issues #620, #384 and #694.
In the file `classes/output/navigation/primary.php` when  _smartmenus_ were enabled the `parent:export_for_template` does not get called ( parent class is `core\navigation\output\primary`).
**Cause of the bug:** The menu with the smartmenu nodes are just merged with the primary navigation and the custommenus via the PHP function `array_merge`. 
**Fix:** Now the smartmenus and the custommenus are merged via array_merge and later merged with the primary menu nodes via the function `merge_primary_and_custom`. This function checks for the active node, the same way it happens when smartmenus are disabled.
Maybe this should also be adjusted when the variable `$mobileprimarynav` gets set, too. …
> Bugfix: set active navigation node when smartmenus are enabled, resoves #620, #384 and #694.

- CHANGES.md
- scss/boost_union/post.scss
Issue: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/655
This should be a quick and easy fix. However I don't know if it has any drawbacks I haven't thought of.
> Bugfix: footer displacement on pages with minimal content, resolves #655.

- CHANGES.md
- scss/boost_union/post.scss
This PR provides explicit width and height for icons in the courseindex drawer for Moodle 4.4.
As mentioned in the issue, this is needed if icons exceed a specific size as seen with some thridparty plugins.
To provide consitency with 4.4. styling, 24px were used as values.
> Fix thirdparty icon size in 4.4 courseindex drawer, resolves #755

- tests/behat/theme_boost_union_contentsettings_footer.feature
- tests/behat/theme_boost_union_contentsettings_staticpages.feature
- tests/behat/theme_boost_union_feelsettings_links.feature
- tests/behat/theme_boost_union_feelsettings_navigation.feature
- tests/behat/theme_boost_union_feelsettings_pagelayouts.feature
- tests/behat/theme_boost_union_goodiesfordesigners.feature
The aim of those two tags is to potentially exclude tests that deal with footer and footnote.
In my place, I modify the .mustache so that the footer and footnote are completely different.
In consequence, the Behat test fail. But in this way, I could exclude the adhering Behat test (by instructing @theme_boost_union&&\~@theme_boost_union_footer&&\~@theme_boost_union_footnote)
> Distinguish behat tests who deal with footer and footnote.

- config.php
Once MDL-75610, this will allow Boost Union to display the activity name in the secure layout.
Testing:
```bash
php admin/tool/behat/cli/init.php -a
php admin/tool/behat/cli/run.php --suite=boost_union --feature="$(pwd)/mod/quiz/accessrule/seb/tests/behat/secure_layout_activity_heading.feature"
```
[x] link your issue in the PR title, using the keyword 'resolves #ISSUE-NUMBER', e.g. 'Feature: Provide the ultimate user experience, resolves #42'
[x] provide any further information that is relevant for peer review and not yet mentioned in the linked issue as a comment in the PR
[x] make sure that the 'Allow edits by maintainers' checkbox is checked when creating the PR. Otherwise, the peer reviewer would not be able to push any review changes to the PR and the communication overhead …
> Enable title in activity header on secure layout, resolved #766

- config.php
Backport of #770 for the MOODLE_405_STABLE branch.
>  Enable title in activity header on secure layout, resolved #766 (405 backport)

- config.php
Backport of #770 for the MOODLE_404_STABLE branch.
> Enable title in activity header on secure layout, resolves #766 (404 backport)

- CHANGES.md
- classes/form/smartmenu_edit_form.php
- classes/form/smartmenu_item_edit_form.php
- classes/smartmenu.php
- classes/smartmenu_item.php
- tests/behat/behat_theme_boost_union.php
- tests/behat/theme_boost_union_feelsettings_blocks.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_dynamiccourses.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_presentation.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_rules.feature
- tests/generator/behat_theme_boost_union_generator.php
- tests/generator/lib.php
This does a bunch of optimisations for the longest-running behat features. See the commit messages for details of what I've done. Further optimisations are possible, but I don't have time to work on this any further at the moment. Hopefully the groundwork of adding the `behat_theme_boost_union` and `behat_theme_boost_union_generator` classes will make it easy for others to make further improvements.
In [my first run of these changes](https://github.com/marxjohnson/moodle-theme_boost_union/actions/runs/11957413640) the tests completed in 2.5 hours, vs the 3.5-4 hours I was getting previously., 
[x] link your issue in the PR title, using the keyword 'resolves #ISSUE-NUMBER', e.g. 'Feature: Provide the ultimate user experience, resolves #42'
[x provide any further information that is …
> Behat optimisations, addresses #765.

- CHANGES.md
- classes/form/smartmenu_edit_form.php
- classes/form/smartmenu_item_edit_form.php
- classes/smartmenu.php
- classes/smartmenu_item.php
- tests/behat/behat_theme_boost_union.php
- tests/behat/theme_boost_union_feelsettings_blocks.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_dynamiccourses.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_presentation.feature
- tests/behat/theme_boost_union_smartmenusettings_menuitems_rules.feature
- tests/generator/behat_theme_boost_union_generator.php
- tests/generator/lib.php
Backport of #767 to the MOODLE_405_STABLE branch.
> Behat optimisations, addresses #765 (405 backport)

- CHANGES.md
- classes/form/flavour_edit_form.php
- db/install.xml
- db/upgrade.php
- lang/en/theme_boost_union.php
- layout/includes/navbar.php
- lib.php
- locallib.php
- tests/behat/behat_theme_boost_union_base_general.php
- tests/behat/theme_boost_union_flavourssettings_look.feature
- tests/behat/theme_boost_union_looksettings_loginpage.feature
- tests/behat/theme_boost_union_looksettings_sitebranding.feature
- version.php
This PR fixes multiple flavour and child-theme related issues:
```
* 2024-12-31 - Child theme support: Fully replicate Boost Union's extra SCSS if a Boost Union Child theme is the current theme, resolves #718, resolves theme_boost_union_child/#5.
* 2024-12-31 - Bugfix / Child theme support: The theme_boost_union_get_pre_scss() and theme_boost_union_get_extra_scss() function used $theme->settings although they should not do that anymore, resolves #791
* 2024-12-31 - Tests: Increase the test coverage for the background image setting, helps to resolve theme_boost_union_child/#5
* 2024-12-31 - Bugfix: In flavours, not setting the brand color / bootstrap colors in a flavour did not result in the global brand color / bootstrap colors being served properly, resolves #790.
* 2024-12-30 - …
```
> PR for multiple flavour and child-theme related issues

- CHANGES.md
- classes/eventobservers.php
- tests/behat/theme_boost_union_smartmenusettings_menuitems_dynamiccourses.feature
- version.php
Fixed the issue where course enrollment and unenrollment now properly update the dynamic course items for users.
> Bugfix: Fix dynamic course items not updating properly based on course role assignments. resolves #749.

- CHANGES.md
- locallib.php
See #627. Essentially only replaces the '1' in the URL string with the correct systemcontextid where applicable. Behat tests should not be changed as fresh installs always for the tests should have $systemcontext -> id = 1.
> Remove assumtion that syscontext->id = 1, resolves #627

- CHANGES.md
- classes/output/core/course_renderer.php
- scss/boost_union/post.scss
- tests/behat/theme_boost_union_looksettings_categoryindexsitehome.feature
This PR fixes the regression of #930 and styles the button on the search page.
> Regression: Course search page did not use the improved course listings anymore, resolves #930

- CHANGES.md
- templates/core_courseformat/local/courseindex/cm.mustache
- templates/core_courseformat/local/courseindex/cm.mustache.upstream
>  Bugfix: Text and media elements (aka. labels) were shown in the course index also in non edit mode, resolves #637

- CHANGES.md
- classes/external/get_fontawesome_icons.php
- tests/behat/theme_boost_union_smartmenusettings_menuitems_presentation.feature
It is strange that this has not been caught by automated tests.
But in fact when doing
```
@javascript
Scenario: Smartmenus: Menu items: Setup - select an icon
When I log in as "admin"
And I navigate to smart menus
And I click on "Create menu" "button"
And I set the following fields to these values:
| Title          | Menu          |
| Menu location(s) | Main |
And I click on "Save and configure items" "button"
And I click on "Add menu item" "button"
And I set the field "Icon" to "folder"
```
the icon autocomplete field breaks.
Maybe it has something to do with speed.
And Behat is faster than my mouse/finger.
I did not manage to break it in the frontend myself.
> Bugfix: Uninitialized $overflow causes smart menu icon pick to fail, resolves #1035

- CHANGES.md
- classes/output/navigation/primary.php
- classes/smartmenu.php
- classes/smartmenu_item.php
- scss/boost_union/post.scss
- templates/theme_boost/navbar.mustache
- tests/behat/theme_boost_union_smartmenusettings_menuitems_presentation.feature
- tests/behat/theme_boost_union_smartmenusettings_menus_presentation.feature
- version.php
Included bootstrap responsive utility classes (d-md-none, d-md-flex, etc.) to control the visibility of the smart menu menubar based on the presence of child items.
> Bugfix: Smart menu: menu bar displayed although there are no items to display, resolves #849.
