CHANGES.md, README.md, lang/en/theme_boost_union.php, lib.php, settings.php, tests/behat/theme_boost_union_looksettings_branding.feature, version.php
With this contribution, the admin can configure the Bootstrap colors Success, Info, Warning and Danger within the GUI.
=> Feature: Bootstrap colors, solves #35

CHANGES.md, README.md, lang/en/theme_boost_union.php, layout/columns2.php, layout/drawers.php, settings.php, tests/behat/theme_boost_union_feelsettings_navigation.feature, version.php
I think this should do the trick.
Requesting review.
Best,
Luca
=> Re-adding activity navigation fixes #100.

CHANGES.md, templates/core/full_header.mustache
=> Bugfix: Unparsable mustache JSON content.

CHANGES.md, scss/boost_union/post.scss
=> Fix: Align horizontal margins for the info banners.

CHANGES.md, scss/boost_union/post.scss
This PR solves the issues with the dark navbar which were brought up in #234 #235 #236
=> Solve multiple issues with dark navbar

CHANGES.md, lib.php
Bug was introduced by PR for #260.
=> #279 - Use of activityiconcolorcommunication fixed

CHANGES.md, scss/boost_union/post.scss
This CSS addition will solve #291
=> Improvement: Add SCSS code for Dash Pro #291

CHANGES.md, README.md, lang/en/theme_boost_union.php, lib.php, settings.php, tests/behat/theme_boost_union_looksettings_branding.feature, version.php
This PR is a DevCamp result at MoodleMootDACH with very warm thanks to [Academic Moodle Cooperation](https://moodle.academic-moodle-cooperation.org/) for providing existing code from their their Boost child theme.
=> Feature: Allow the admin to overwrite the modules purpose, solves #288.

CHANGES.md, locallib.php
Thanks @radzisze for the report and the proposal on how to tackle this!
=> Fix PHPUnit runs with Boost Union, solves #305

CHANGES.md, lib.php
This PR should solve #325 and #326. There is no obvious case which would trigger the prerequisites for these issues up to now, but if these prerequisites are there, the resulting bug is avoided.
=> Bugfix: If block settings were not set, the SCSS was not compiled, solves #325.

CHANGES.md, locallib.php
I do not know why my system did not have a CSS cached folder though…
=> Bugfix: Warning if no CSS cached folder is present on updating, solves #330.

CHANGES.md, templates/theme_boost/drawers.mustache
This adds conditionally of OffCanvas module loading when offcanvas region is enabled.
=> #343 Only add load OffCanvas module when offcanvas region is enabled

.github/ISSUE_TEMPLATE/for-support-request-please-visit-our-forum-.md, .github/ISSUE_TEMPLATE/issue.md
Changed template "Issue" and added new template for support requests.
=> Update issue templates

lang/en/theme_boost_union.php
This needs no CHANGES.md entry or peer review.
=> Wherever spelled correctly.

CHANGES.md, tests/behat/theme_boost_union_looksettings_activitybranding.feature, tests/behat/theme_boost_union_looksettings_sitebranding.feature
This PR adds some more Behat tests for scenarios which have not been covered before. There is no particular issue for adding these tests, just comments in the feature files which are solved by this PR.
=> Add some more tests to improve the Behat coverage

CHANGES.md, README.md, lang/en/theme_boost_union.php, lib.php, settings.php, tests/behat/theme_boost_union_looksettings_page.feature, version.php
In addition to fixing #74, I enhanced the test coverage of the similar width settings on the same settings page
=> Feature: Allow the admin to set the course index and block drawer width, solves #74.

CHANGES.md, README.md, classes/smartmenu_item.php
[ ] link your issue in the PR title, using the keyword 'resolves #ISSUE-NUMBER', e.g. 'feat: provide the ultimate user experience, resolves #42'
[ ] provide any further information that is relevant for peer review and not yet mentioned in the linked issue
[ ] submit your PR in draft status to run the automated checks and review the results
[ ] in case any checks fail solve the mentioned errors by …
=> Load custom field config fix, resolves #576

.github/workflows/moodle-plugin-ci.yml
A lot less warnings with this.
=> Changing moodle-plugin-ci.yml to remove annotations, resolves #591.

CHANGES.md, README.md, lang/en/theme_boost_union.php, layout/columns2.php, layout/drawers.php, layout/includes/navbar.php, scss/boost_union/post.scss, settings.php, templates/core/user_menu.mustache, tests/behat/theme_boost_union_feelsettings_navigation.feature, version.php
The result of this PR will look like this in the user menu:
=> Feature: Show the logged-in user's full name in the user menu, resolves #439.

templates/course-hint-hidden.mustache
Trivial change, so I omitted a CHANGES.md entry.
Hope this is okay.
=> Bugfix: Parsable Mustache example JSON, resolves #644.

CHANGES.md, tests/behat/theme_boost_union_contentsettings_infobanners.feature
See https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/734#issuecomment-2435220111 for details
=> Tests: Try to fix Behat error 'Warning: Undefined array key 1' on Moodle 4.5, resolves #734.

smartmenus/menulib.php, tests/behat/theme_boost_union_smartmenusettings_menuitems_rules.feature, tests/behat/theme_boost_union_smartmenusettings_menus_rules.feature
=> Fix cohort/rule deletion, resolves #737

smartmenus/menulib.php, tests/behat/theme_boost_union_smartmenusettings_menuitems_rules.feature, tests/behat/theme_boost_union_smartmenusettings_menus_rules.feature
=> Fix cohort/rule deletion, resolves #737 (MOODLE_403_STABLE)

smartmenus/menulib.php, tests/behat/theme_boost_union_smartmenusettings_menuitems_rules.feature, tests/behat/theme_boost_union_smartmenusettings_menus_rules.feature
=> Fix cohort/rule deletion, resolves #737 (MOODLE_401_STABLE)

smartmenus/edit.php, smartmenus/edit_items.php
Theme boost union
should be
Theme Boost Union
=> Replace lower case Theme boost union by upper case.

CHANGES.md, classes/form/smartmenu_edit_form.php, classes/form/smartmenu_item_edit_form.php, classes/smartmenu.php, classes/smartmenu_item.php, tests/behat/behat_theme_boost_union.php, tests/behat/theme_boost_union_smartmenusettings_menuitems_dynamiccourses.feature, tests/behat/theme_boost_union_smartmenusettings_menuitems_presentation.feature, tests/generator/behat_theme_boost_union_generator.php, tests/generator/lib.php
Backport of #767 to the MOODLE_404_STABLE branch.
=>  Behat optimisations, addresses #765 (404 backport)

CHANGES.md, README.md, lang/en/theme_boost_union.php, lib.php, locallib.php, scss/boost_union/post.scss, settings.php, tests/behat/theme_boost_union_looksettings_sitebranding.feature, version.php
=> Extending navbar logo settings with maxwidth - resolves #544

CHANGES.md, README.md, templates/course-hint-guestaccess.mustache, templates/course-hint-hidden.mustache, templates/course-hint-selfenrol.mustache, templates/course-hint-switchedrole.mustache
=> Replaces deprecated "media" CSS classes with supported equivalents.

CHANGES.md, classes/output/core/course_renderer.php, classes/util/course.php
=> Bugfix: control use of boost union coursebox, resolves #895

CHANGES.md, scss/boost_union/post.scss, templates/core/moremenu.mustache, templates/theme_boost/language_menu.mustache, templates/theme_boost/language_menu.mustache.upstream
Bugfix: Language selector menu for visitors did not respect navbar color, resolves #966.
Bugfix: Main navigation more menu did not respect navbar color, resolves #967
=> Bugfixes for colored navbar

templates/theme_boost/language_menu.mustache
=> Bugfix: no boots allowed here.

CHANGES.md, lang/en/theme_boost_union.php, layout/includes/navbar.php, settings.php, templates/core/user_menu.mustache, tests/behat/theme_boost_union_feelsettings_navigation.feature
Please cross check whether the setting is in the right spot.
=> Display "Login" link on site home as button, resolves #979
